POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2lhIiwiaWQiOiI2ODdjMTRjNGUyNzk2MzgwNmM5MThmY2YiLCJpYXQiOjE3NTI5NjY4MDN9.9HQceHV2S-ASkiKRTeYrC3ty_H4IAjSgFrZlkBB29iA

{
  "content": "Single page apps use token based auth",
  "important": true
}